### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by zmatez** [AtomMaterialUI/Image-Icon-Viewer#72]
**Describe the bug**

IT LAGS THE IDE SO MUCH. It didn't before, but for like a month it's just too much, I had to disable this plugin. Directories when I open them in a tree keep saying "loading..." for infinite time. IDE lag spikes like every 5s and it was that annoying I reinstalled my Windows as I couldn't find the issue and writing any code was a tragedy.

**To Reproduce**

Have a large project with lots of directories and files (in my case - react app + nodejs server in same dir)

1.

**Expected Behavior**

Good performance

**Environment**

PhpStorm 2024.2.1
Build #PS-242.21829.154, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6144M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.github (242.21829.162)
  org.jetbrains.plugins.gitlab (242.21829.162)
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  com.bluewaitor.tsReact (1.4.0)
  com.darkyen.darkyenustimetracker (1.5.3)
  net.seesharpsoft.intellij.plugins.csv (3.4.0-242)
  com.mallowigi (97.0.0)
  com.mallowigi.colorHighlighter (18.0.0)
(this plugin is disabled)
Image Icon Viewer 15.0.0

**Screenshots**

**Comment by mallowigi** [comment]
I know, I also started encountering this problem since the 2024.2 update. I'll definitely try to find a fix but you're welcome to help rather than shout.
